library(rmarkdown)
library(knitr)
---
#Data Science Project 
#Sean Konovitz
#Crime and Census Attributes in Buffalo, New York  
---

# Introduction
I will be combining crime data using an API from Open Data Buffalo and census data using the census API. The crime data is a daily updated dataset of crime incidents within the city of Buffalo provided by the Buffalo Police Department. This dataset includes the type of incident, such as theft and assault, as well as the time, date, and coordinates. The census data is using American Community Survey (ACS)five-year estimates at the census tract geography level.



# Materials and methods
1. For the crime data, the package RSocrata was used to read the data from Open Data Buffalo into R, as Open Data Buffalo is a website "powered by" Socrata. Socrata is a software company that forms partnerships with governments, such as Buffalo's in 2017 to provide accessible data. In order to open it with the RSocrata package in R, one has to create an account with the site and aquire an app token. This token, along with the username, password and api link are utilized with the function read.socrata() to get it available in R. In this case, it is the crime incidents dataset. As far as geography, spatial data with the 79 census tracts in Buffalo was obtained as well from Open Data Buffalo. To read this into R, the function readShapePoly() from the maptools package was used with the file path to the shapefile.

Note: I will have to put data in data folder before it would be able to run 


```library("RSocrata")

crime <- read.socrata(
  "https://data.buffalony.gov/resource/d6g9-xbgu.json",
  app_token = "y67OCQdGIHD80tqceGSZV8rj1",
  email     = "seankono@buffalo.edu",
  password  = "Skbuff66$")
```
```
library(maptools)
buffalotracts<- readShapePoly("C:/Users/Asus/Documents/R/R(Git)/geo503-2018-seankono/geo_export_c9004500-af2b-4c4d-8cde-4de9d5831f2e.shp")

```
2. For the census data, the packages tidycensus and tidyverse allowed for the data to be incorporated easily into R. First, one needs to obtain a census API key from https://api.census.gov/data/key_signup.html. Then, the key is put in the census_api_key() and Sys.getenv() functions. 

To get the data itself, the decision has to be made between the decennial, which is performed every ten years, or the Amercan Community Survey (ACS), which are five year estimates with a margin of error. I decided to go with the ACS, as it seemed to provide more variables that may be useful to the project. 

To get the acs data, get_acs() is used and the state, county, geography, variables, and geometry. Since the study area is Buffalo, "NY" and "Erie" were used while "tract" was chosen as the geography since I felt it fits best with the census data. I could have went smaller, to census block groups, but with smaller populations the data may be less reliable. I chose median household income as the variable using the code "B19013_001", since median income is a common measure used. I still change it to a different variable or incorporate an additional one. 

```
library(tidycensus)
library(tidyverse)

census_api_key("a228276714dbd52068673939d5ccb03af28a4cab", overwrite = FALSE, install = TRUE)
Sys.getenv("a228276714dbd52068673939d5ccb03af28a4cab")

erie<- get_acs(state = "NY", county = "Erie", geography = "tract", 
                  variables = "B19013_001", geometry = TRUE)
```
3. To get just the census tracts for Buffalo and not all of Erie County, I merged the Buffalo tracts and the census data by "geoid10" and "GEOID", which have the same values corresponding to census tract. By setting all.y=FALSE, that made it so only the 79 Buffalo tracts and their data remains. 

```

joined.tracts <- merge(bufftract, erie, by.x = "geoid10", by.y = "GEOID",
                       all.y = FALSE)
```
4. Next is to enable the crime data to be turned into points and then likely count the points in each polygon tract which will probably use the point.in.polygon function. This will be done Monday or by Tuesday. 


# Results

Still to be determined. Should be able to be updated Monday or Tuesday

# Conclusions

To be determined from the results

# References

https://data.buffalony.gov/resource/d6g9-xbgu.json

https://data.buffalony.gov/d/ts8p-7v76?category=Government&view_name=U-S-Census-Tracts-in-BuffaloOpens in new window.

https://walkerke.github.io/tidycensus/articles/spatial-data.html

